
bloom_match_up_index:
    path:      /index
    defaults: { _controller: BloomMatchUpBundle:Default:index }

bloom_match_up_classement:
    path:      /classement
    defaults: { _controller: BloomMatchUpBundle:Default:classement }

bloom_match_up_homepage:
    path:      /
    defaults: { _controller: BloomMatchUpBundle:Default:homepage}

bloom_match_up_matchup:
    path:      /matchup
    defaults: { _controller: BloomMatchUpBundle:Default:matchup }

bloom_match_up_profil:
    path:      /profil/{idAdversaire}
    defaults: { _controller: BloomMatchUpBundle:Default:profil, idAdversaire: 1 }

bloom_match_up_afficher_poule:
    path:      /afficher-poule
    defaults: { _controller: BloomMatchUpBundle:Default:afficherPoule }

bloom_match_up_entrer_resultat:
    path:      /entrer-resultat
    defaults: { _controller: BloomMatchUpBundle:Default:entrerResultat }

bloom_match_up_afficher_poule:
    path:      /afficher-poule/{numeroPoule}
    defaults: { _controller: BloomMatchUpBundle:Default:afficherPoule, numeroPoule: 0 }

bloom_match_up_admin:
    path:     /admin
    defaults: { _controller: BloomMatchUpBundle:Admin:dashBoard }

bloom_match_up_admin_supprimer_profil:
    path:     /admin/supprimer-profil
    defaults: { _controller: BloomMatchUpBundle:Admin:supprimerProfil }

bloom_match_up_admin_selectionner_profil:
    path:     /admin/selectionner-profil
    defaults: { _controller: BloomMatchUpBundle:Admin:selectionnerProfil }

bloom_match_up_admin_modifier_profil:
    path:     /admin/modifier-profil
    defaults: { _controller: BloomMatchUpBundle:Admin:modifierProfil }

bloom_match_up_admin_modifier_resultat:
    path:     /admin/modifier-resultat/{idProfil}
    defaults: { _controller: BloomMatchUpBundle:Admin:ModifierResultat }

bloom_match_up_admin_generer_poule:
    path:      /admin/genererPoule
    defaults: { _controller: BloomMatchUpBundle:Admin:genererPoule }