
bloom_match_up_index:
    path:      /index
    defaults: { _controller: BloomMatchUpBundle:Default:index }

bloom_match_up_classement:
    path:      /classement
    defaults: { _controller: BloomMatchUpBundle:Default:classement }

bloom_match_up_homepage:
    path:      /
    defaults: { _controller: BloomMatchUpBundle:Default:homepage}

bloom_match_up_matchup:
    path:      /matchup
    defaults: { _controller: BloomMatchUpBundle:Default:matchup }

bloom_match_up_profil:
    path:      /profil/{idAdversaire}
    defaults: { _controller: BloomMatchUpBundle:Default:profil, idAdversaire: 1 }

bloom_match_up_generer_poule:
    path:      /genererpoule
    defaults: { _controller: BloomMatchUpBundle:Default:genererpoule }

bloom_match_up_afficher_poule:
    path:      /afficherpoule
    defaults: { _controller: BloomMatchUpBundle:Default:afficherpoule }

bloom_match_up_entrer_resultat:
    path:      /entrerresultat
    defaults: { _controller: BloomMatchUpBundle:Default:entrerresultat }

bloom_match_up_afficher_poule:
    path:      /afficherpoule/{NumeroPoule}
    defaults: { _controller: BloomMatchUpBundle:Default:afficherpoule, NumeroPoule: 0 }

bloom_match_up_admin:
    path:     /admin
    defaults: { _controller: BloomMatchUpBundle:Admin:dashboard }

bloom_match_up_admin_ajouter_profil:
    path:     /admin/ajouter-profil
    defaults: { _controller: BloomMatchUpBundle:Admin:ajouterProfil }

bloom_match_up_admin_supprimer_profil:
    path:     /admin/supprimer-profil
    defaults: { _controller: BloomMatchUpBundle:Admin:supprimerProfil }

bloom_match_up_admin_modifier_profil:
    path:     /admin/modifier-profil
    defaults: { _controller: BloomMatchUpBundle:Admin:modifierProfil }

bloom_match_up_admin_modifier_resultat:
    path:     /admin/modifier-resultat
    defaults: { _controller: BloomMatchUpBundle:Admin:modifierResultat }