parameters:
#    bloom_match_up.example.class: Bloom\MatchUpBundle\Example

services:
#    bloom_match_up.example:
#        class: %bloom_match_up.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
