parameters:
#    bloom_match_up.example.class: Bloom\MatchUpBundle\Example

services:
    bloom_match_up.form.type.AdversairePouleFormType:
        class: Bloom\MatchUpBundle\Form\Type\AdversairePouleFormType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: bloom_adversaire_poule }

    bloom_match_up.form.type.AdversairePouleScoreFormType:
        class: Bloom\MatchUpBundle\Form\Type\AdversairePouleScoreFormType
        tags:
            - { name: form.type, alias: bloom_adversaire_poule_score }

#    bloom_match_up.example:
#        class: %bloom_match_up.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
